name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    name: Package py to exe

    strategy:
      matrix:
        os: [ windows-latest ]
        python-version: ["3.10"]
        # os: [ ubuntu-latest, macos-latest, windows-latest ]
        # os: [ ubuntu-latest ]
        # python-version: ["3.9", "3.10"]

    runs-on: ${{ matrix.os }}


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller impacket

      - name: Package Artifacts
        run: |
          pyinstaller main.py --onefile

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
